all: memleak test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 test11 test12

memleak: memleak.c
test1: test1.c
test2: test2.c
test3: test3.c
test4: test4.c
test5: test5.c
test6: test6.c
test7: test7.c
test8: test8.c
test9: test9.c
test10: test10.c
test11: test11.c
test12: test12.c
